CREATE TABLE topic_content_response (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `topic_content_id` INT UNSIGNED NOT NULL COMMENT '所属话题内容id',
  `user_id` INT UNSIGNED NOT NULL COMMENT '回帖人id',
  `leaving_message` TEXT COMMENT '回帖内容',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='话题内容回帖表';
