mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.dragon.cate.dao.meta
  configuration:
    default-enum-type-handler: com.dragon.cate.dao.handler.IntValueEnumTypeHandler

spring:
  freemarker:
      template-loader-path: classpath:templates
      suffix: .html
       
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.230.222/dragon?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz!QAZ
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j2



